# 1. Configuración del Servidor
quarkus.http.port=8082

# 2. Configuración de la Base de Datos - PostgreSQL
# Si usas Docker local, el host suele ser localhost
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usuario_cordillera
quarkus.datasource.password=cordillera_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/db_users
quarkus.datasource.devservices.enabled=false
# quarkus.datasource.jdbc.url=jdbc:postgresql://db-users:5432/db_users

# 3. Estrategia de Hibernate (ORM)
# 'update' crea las tablas automáticamente si no existen (ideal para desarrollo)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
# quarkus.hibernate-orm.log.sql=true

# 4. Configuración de OpenAPI (Swagger) para testear
quarkus.swagger-ui.always-include=true